//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessDiary
    {
        public int Business_id { get; set; }
        public System.DateTime Date { get; set; }
        public double Start_time { get; set; }
        public double End_time { get; set; }
    }
}
