//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.Appointment = new HashSet<Appointment>();
        }
    
        public int Business_Number { get; set; }
        public string Name { get; set; }
        public string AddressStreet { get; set; }
        public string AddressCity { get; set; }
        public string Professional_ID_number { get; set; }
        public string About { get; set; }
        public string phone { get; set; }
        public string Facebook_link { get; set; }
        public string Instagram_link { get; set; }
        public string AddressHouseNumber { get; set; }
        public Nullable<double> LetCordinate { get; set; }
        public Nullable<double> LongCordinate { get; set; }
        public string Is_client_house { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual Professional Professional { get; set; }
        public virtual Professional Professional1 { get; set; }
    }
}
