//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canceled_Appointment
    {
        public int Number_appointment { get; set; }
        public System.DateTime Date { get; set; }
        public int Business_Number { get; set; }
        public Nullable<int> Type_Treatment_Number { get; set; }
        public string ID_Client { get; set; }
        public int Cancel_id { get; set; }
        public string Canceled_By { get; set; }
    }
}
